name: Deploy Stock Dashboard

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Ubuntu VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e

            # Navigate to your project folder
            cd /home/azureuser/stock_dashboard_proj

            # Pull latest changes from GitHub
            git pull origin main

            # Install/update dependencies using the venv's Python
            /home/azureuser/venvs/project_env/bin/python -m pip install --upgrade -r requirements.txt

            # Run the Python script using the venv's Python
            /home/azureuser/venvs/project_env/bin/python stock_dashboard.py


            # Log deployment timestamp
            echo "Deployed at $(date)" >> deploy.log


